---
title: "week 5 tutorial"
author: "Anna Li"
date: "2/1/2022"
output: pdf_document
---

```{r setup, include = FALSE}
library("usethis")
```

## Paper 1: Transcribe Introduction
### Paper: On Reproducible Research by Roger Koenker and Achiim Zeileis

"The renowned dispute between Gauss and Legendre over priority for the invention of the mehtod of least squares might have been resolved by Stigler (1981). A calculation of the earth's ellipticity reported by Gauss in 1799 alluded to the use of meine Methode; had Stigler been able to show that Gauss's estimate was consistent with the least squares solution using the four observations available to Gauss, his claim that he had been using the method since 1795 would have been strongly vindicated. Unfortunately, no such computation could be reproduced leaving the dispute in that limbo all too familiar in the computational sciences. 
The question that we would like to address here is this: 200 years after Gauss, can we do better? What can be done to improve our ability to reproduce computational results in econometrics and related fields? Our main contention is that recent software developments, notably in the opensource community, make it much easier to achieve and distribute reproducible reserach. 

What do we mean by reproducible research? Buckheit and Donoho (1995) have defined what de Leeuw (2001) has called Claerbout's Principle: "An article about computational science in a scientific publication is not the scholarship itself, it is merely advertising of the scholarship.The actual scholarship is the complete software development environment and the complete set of instructions which generated the figures."We view this as a desirable objective for econometric research. See Schwab et al. (2000) for further elaboration of this viewpoint. 

The transition of econometrics from a handicraft industry (Wilson, 1973, Goldberger, 2004) to the modern sweatshop of globally interconnected computers has been a boon to productivity and innovation, but sometimes seems to be a curse. Who among us expected to be in the "software development" business? And yet many of us find ourselves precisely in this position, and those who are not, probably should be. As we will argue below, software development is no longer something that should be left to specialized commercial developers, but instead should be an integral part of the artisanal econometric research process. Effective communication of research depends crucially on documentation and distribution of related software and data. 

Some journals, such as the Journal of Applied Econometrics (JAE, http://JAE.Wiley.com/), support authors in this task by providing data archives (MacKinnon, 2007). However, a more integrated approach encompassing data, software, empirical analysis, and documentation is often desirable to facilitate replication of results. 

## Paper 2: Rewrite Introduction
### Paper: Asset Prices in an Exchange Economy by Robert E. Lucas Jr

The paper looks to theoretically examine the relationship between exogenous determined productivity changes and market determined movement in asset prices for a one-good, pure exchange economy with identical consumers.  The model's equation generalizes the Martingale property as context to view a price series' failure as irrationality evidence. The analysis assumes that price reflects all available information and people are rational. The paper replicates the result of previous papers in the literature fields for the Martingale property.

## Paper 3: Transcribe Abstract
### Paper: Seeing Like a Market by Marion Fourcade and Kieran Healy

What do markets see when they look at people? Information dragnets increasingly yield huge quantities of individual-level data, which are analyzed to sort and slot people into categories of taste, riskiness, or worth. These tools deepen the reach of the market and define new strategies of profit-making. We present a new theoretical framework for understanding their development. We argue that (a) modern organizations follow an institutional data imperative to collect as much data as possible; (b) as a result of the analysis and use of this data, individuals accrue a form of capital flowing form their positions as measured by various divital scoring and ranking methods; and (c) the facticity of these scoring methods makes them organizational devices with potentially stratifying effects. They offer firms new opportunities to structure and price offerings to consumers. For individuals, they create classification situations that identify shared life-chances in product and service markets. We discuss the implications of these processes and argue that they tend toward a new economy of moral judgment, where outcomes are experienced as morally deserved positions based on prior good actions and good tastes, as measured and classified by this new infrastructure of data collection and analysis. 

## Paper 4: Rewrite Abstract (4 sentences)
### Paper: Individuals, Institutions, and Innovation in the Debates of the French Revolution by Alexander T. J. Barron, Jenny Huang, rebecca L. Spang, and Simon DeDeo

The paper uses quantitative analysis to investigate how the French Revolutions' first parliament managed innovation.
Overall, the parliament wanted to innovate, with the right often trying to preserve traditions. 
Using reconstructed transcripts, significant factors that swayed the debate outcomes was power,coming internally from executive positions on the parliament and externally as power to dispose the parliament as a whole. 
Results reveal that great orators have public attention, but the typically left deputies who were parliament executives were more influential in shaping the revolutionary legislation. 

## Paper 5: Rewrite Abstract Version 2, Simplified 
### Paper: Individuals, Institutions, and Innovation in the Debates of the French Revolution by Alexander T. J. Barron, Jenny Huang, rebecca L. Spang, and Simon DeDeo

Refer to Paper 4: Rewrite Abstract for version 1 of abstract

The paper uses numbers to find how the first rising changed law. The left party wanted to change, but the right wanted to stay the same. Using old letters of the talks about what to do about the law, power was important in getting what was wanted. Power could be from position or from how the person could hurt and remove the state. The paper found that good speakers got the most attention from people, but the people who actually mostly got what they wanted changed and written in the law were the people from higher positions in the state. These people who got what they wanted were also mostly from the left party. 


## Paper 6: 3 Points I Like
### Paper: Smoking and Carcinoma of the Lung by Richard Doll and A. Bradford Hill
1. The first point I enjoyed was how the paper describes the context that the study is taken within. It provides the number of deaths in proportion to the entire population, discusses world events that may also be a cause of deaths, and also how better diagnosis may be a reason for the higher number of cases. This provides a framework for the readers to understand before learning about the specifics of the study. 

2. The second point I liked was how the authors discussed the flaw of their data collection methods. Particularly they discussed having non-response bias. However, no specific group was intentionally chosen to be non-response, so the authors address it as a limitation that should not have much effect on the effectiveness of the overall paper's investigations.

3. The third point I enjoyed was how the authors discussed association, using it as only one of the key points of their argument. First, the authors mention association does not necessarily mean causation, a point that is very important and constantly discussed when looking at relationships. However, the paper takes the discussion a step further. The authors discuss factors that provide stronger evidence supplementing the association of smoking and carcinoma. Therefore,with multiple pieces of evidence including the association, the paper strongly concludes that smoking is an important factor in carcinoma production of the lung. 

## Paper 7: 1 Point I Dislike
### Paper: The Mundanity of Excellence: An Ethnographic Report on Stratification and Olympic Swimmers
One point that I disliked were how some of the footnotes were very personal. For example, foot note 16 states "These fast swimmers who come to slow meets are called hot dogs, showoffs, or even jerks. (Personal
 observations.)" While it does add an element of humour, I do not think it adds anything very valuable to the paper and the argument proposed overall. 

## References
Barron, Alexander TJ, Jenny Huang, Rebecca L Spang, and Simon DeDeo. 2018. “Individuals, Institutions, and Innovation in the Debates of the French Revolution.”

Chambliss, Daniel F. 1989. “The Mundanity of Excellence: An Ethnographic Report on Stratification and Olympic Swimmers.” Sociological Theory 7 (1): 70–86.

Doll, Richard, and A Bradford Hill. 1950. “Smoking and Carcinoma of the Lung.” British Medical Journal 2 (4682): 739.

Fourcade, Marion, and Kieran Healy. 2017. “Seeing Like a Market.” Socio-Economic Review 15 (1): 9–29.

Heckman, James J. 1979. “Sample Selection Bias as a Specification Error.” Econometrica: Journal of the Econometric Society, 153–61.

Lucas Jr, Robert E. 1978. “Asset Prices in an Exchange Economy.” Econometrica: Journal of the Econometric Society, 1429–45.

Koenker, Roger, and Achim Zeileis. 2009. “On Reproducible Econometric Research.” Journal of Applied Econometrics 24 (5): 833–47.
